Using Bootstrap - Milestone 1
verissimohenry/Newsweek pull request #1
Opened 2021-03-08 10:31 UTC by verissimohenry

Using Bootstrap - Milestone 1 to create a Newsweek page

2021-03-08 18:07 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @verissimohenry and @tongoonamujera! 👋 

You have done an amazing job with this milestone! It looks really good 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [x] Check my comments for more changes.

- [x] Some of your css styles can be done with bootstrap classes. Take a look at your css file again and use this [cheatsheet](https://hackerthemes.com/bootstrap-cheatsheet/) to see what can be done with bootstrap instead. 
****
Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-03-08 18:07 UTC, BrittanyBlake commented on index.html
> +  </div>
- [x] This main navigation menu should be using the `<nav/>` tag as you should be using [semantic html](https://www.w3schools.com/html/html5_semantic_elements.asp).
Screenshot from pathwright 👇🏾 
<img width="260" alt="Screen Shot 2021-03-08 at 6 42 27 PM" src="https://user-images.githubusercontent.com/48804258/110359655-0a0ec580-803e-11eb-8bb8-ed59bad0b3e2.png">

- [x] You are missing the search form in the main navigation menu
your clone 👇🏾 
<img width="1440" alt="Screen Shot 2021-03-08 at 6 59 02 PM" src="https://user-images.githubusercontent.com/48804258/110361476-5b1fb900-8040-11eb-8a46-cb8054c24666.png">

the original page 👇🏾 
<img width="1314" alt="Screen Shot 2021-03-08 at 6 59 13 PM" src="https://user-images.githubusercontent.com/48804258/110361488-6246c700-8040-11eb-9131-03c920d33e74.png">

- [x] The spacing and alignment of the elements could be improved.

2021-03-08 18:07 UTC, BrittanyBlake commented on index.html
> +  </div>
### **GENERAL**
- [x] The NewsWeek logo should be wrapped in an `<a/>` tag.
Screenshot from requirements 👇🏾 
<img width="241" alt="Screen Shot 2021-03-08 at 6 45 12 PM" src="https://user-images.githubusercontent.com/48804258/110359965-6c67c600-803e-11eb-8867-98cb734f6028.png">

### **DESKTOP**
- [x] The logo should also be centered on the page, it is not centered on my browser.
Your clone 👇🏾 
<img width="1440" alt="Screen Shot 2021-03-08 at 6 46 17 PM" src="https://user-images.githubusercontent.com/48804258/110360094-928d6600-803e-11eb-8972-a7918f7003cb.png">
The original page 👇🏾 
<img width="1321" alt="Screen Shot 2021-03-08 at 6 46 57 PM" src="https://user-images.githubusercontent.com/48804258/110360169-ab961700-803e-11eb-9c16-983d158ec2ca.png">

### **TABLET & MOBILE**

- [x] The elements aren't properly aligned on the tablet and mobile screen sizes.
Your clone on Tablet 👇🏾 
<img width="591" alt="Screen Shot 2021-03-08 at 6 49 08 PM" src="https://user-images.githubusercontent.com/48804258/110360411-f879ed80-803e-11eb-9cf9-3c8fbbdfda22.png">

Your clone on Mobile 👇🏾 
<img width="457" alt="Screen Shot 2021-03-08 at 6 50 38 PM" src="https://user-images.githubusercontent.com/48804258/110360586-2eb76d00-803f-11eb-949c-cd0fa920be45.png">

The original page on Tablet 👇🏾 
<img width="581" alt="Screen Shot 2021-03-08 at 6 49 25 PM" src="https://user-images.githubusercontent.com/48804258/110360440-03348280-803f-11eb-9ff7-9a32f318c073.png">

The original page on Mobile 👇🏾 
<img width="442" alt="Screen Shot 2021-03-08 at 6 50 59 PM" src="https://user-images.githubusercontent.com/48804258/110360609-3aa32f00-803f-11eb-88c4-3dfd357e3a5a.png">

2021-03-08 18:07 UTC, BrittanyBlake commented on index.html
> +      <div class="col-lg-3 pt-lg-3 mt-lg-4 text-white d-none d-lg-block">Wed, Jan 20, 2021</div>
- [x] The date should not wrap to the other line.
Your clone 👇🏾 
<img width="168" alt="Screen Shot 2021-03-08 at 6 54 26 PM" src="https://user-images.githubusercontent.com/48804258/110360991-b56c4a00-803f-11eb-8590-908bec718ab1.png">
The original page 👇🏾 
<img width="231" alt="Screen Shot 2021-03-08 at 6 54 40 PM" src="https://user-images.githubusercontent.com/48804258/110361017-be5d1b80-803f-11eb-8f06-ac9a8d7f7389.png">

2021-03-08 18:07 UTC, BrittanyBlake commented on index.html
> +          <a href="" class="lg1"><span class="d-none d-lg-block d-md-block d-sm-block">LOGIN</span></a>
- [x] The login button should change to an icon on mobile screens.
Your clone 👇🏾 
<img width="457" alt="Screen Shot 2021-03-08 at 6 50 38 PM" src="https://user-images.githubusercontent.com/48804258/110360586-2eb76d00-803f-11eb-949c-cd0fa920be45.png">

The original page👇🏾 
<img width="442" alt="Screen Shot 2021-03-08 at 6 50 59 PM" src="https://user-images.githubusercontent.com/48804258/110360609-3aa32f00-803f-11eb-88c4-3dfd357e3a5a.png">

2021-03-08 18:07 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes `text-decoration-none` and `text-white`

2021-03-08 18:07 UTC, BrittanyBlake commented on style.css
> +  display: block;
- [ ] This can be done with the bootstrap class `d-block`

2021-03-08 18:07 UTC, BrittanyBlake commented on style.css
> +}
- [ ] You can make your footer stick to the bottom by adding the following bootstrap class `fixed-bottom`

2021-03-09 12:14 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @verissimohenry and @tongoonamujera  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] Remove the `.vscode` folder from your project. It's not related to the codes.
- [x]  You are still missing the search form in the main navigation menu
your clone => You have added a search icon, but that doesn't mean a search form. [Refer to this resource](https://www.w3schools.com/html/html_forms.asp) to know how to add html form
- [x] The NewsWeek logo should be wrapped in an <a/> tag. => It was required in the previous review
- [x] The elements aren't properly aligned on the tablet and mobile screen sizes.

=> Footer on mobile screens (width 320px)

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2021-03-09 14-00-46](https://user-images.githubusercontent.com/56886064/110467810-219e8a80-80e0-11eb-9a2c-34eba41eb29e.png) | ![Screenshot from 2021-03-09 14-00-37](https://user-images.githubusercontent.com/56886064/110467850-2bc08900-80e0-11eb-9c34-c78f4f0057ad.png) |\

:point_right: Could you see the difference :question: :question: :question: 

=> Navbar on mobile screens (width 320px)

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2021-03-09 14-00-18](https://user-images.githubusercontent.com/56886064/110467961-50b4fc00-80e0-11eb-8ca7-882f78b0c220.png) | ![Screenshot from 2021-03-09 14-00-06](https://user-images.githubusercontent.com/56886064/110467989-5b6f9100-80e0-11eb-889f-a71711b37f0d.png)|

:point_right: Could you see the difference :question: :question: :question: 

- [x] As this project's main focus is the usage of bootstrap, you should focus on using Bootstrap utility classes instead of writing your own css styles. Currently you have al lot of css properties which could be removed and replaced by bootstrap classes. For example the `display: none;` can be replaced by `.d-none`, `color: white;` can be replaced by `.text-white` :point_left: Kindly revise your css file, and refer to [this resource](https://getbootstrap.com/docs/5.0/getting-started/introduction/) and [this one](https://www.w3schools.com/bootstrap4/bootstrap_utilities.asp) to refactor all of the styles which have alternatives in bootstrap.
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-03-09 16:10 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @verissimohenr**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] you should settle on one way for positioning your elements. for instance, in the navbar you used flexbox and relative positioning. you should just stick with flexbox. in this case, using flexbox with justify-content and align-items properties should simply do the trick. and it would also make it a lot easier to make the navbar responsive.
- [x]  the font-size in the sun-navbar is too small, make sure to enlarge it.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-03-09 21:00 UTC, lekegitrepo approved these changes
## Status: Approved :heavy_check_mark:
### Good job Team :+1:
#### This project is approved :white_check_mark:

#### _Reviewed by Temitayo Adeleke_

2021-03-11 07:17 UTC, merged